### ISSUE TITLE
Indication about conference data been already loaded

### ISSUE THREAD

**Issue by oshadura** [vgvassilev/hepcon-config#11]
In Conference menu, there is no way to see if the data was loaded already or not, clicking load data with  re-trigger loading data from scratch.

Screenshot: https://drive.google.com/file/d/0B4kgVgxHzgwcQ2FsYmxLNnJTODVDUjktYS1rN3JXQXBEckY0/view?usp=sharing

**Comment by mvassilev** [comment]
Would it be ok if we add a datetime field when was the last sync?

**Comment by oshadura** [comment]
Thank you! It will be great!

**Comment by mvassilev** [comment]
Does this look ok?
https://www.dropbox.com/s/iybfv9d98z9xwtu/Screenshot_1527340606.png?dl=0

The idea is to have the currently loaded conference designated.

**Comment by oshadura** [comment]
Yes! it looks good! I will close issue, thank you!
