### ISSUE TITLE
Colour of text in menu [OnePlus 5t]

### ISSUE THREAD

**Issue by oshadura** [vgvassilev/hepcon-config#13]
I don't know why, but on OnePlus 5t colour of text in menu is acid pink.

Screenshot: https://drive.google.com/file/d/0B4kgVgxHzgwcVUkxT3FfZUY4RERmR3BQMGJBM05haDVvNjdJ/view?usp=sharing

**Comment by mvassilev** [comment]
It was because no color was set and I guess a default one was used.
Now it looks like that: https://www.dropbox.com/s/615680vthp9xnoi/Screenshot_1527427919.png?dl=0
