### ISSUE TITLE
Change the color of the font in the session kind boxes

### ISSUE THREAD

**Issue by vgvassilev** [vgvassilev/hepcon-config#22]
![c5cca0e2-fd43-4033-83d2-5476f11d2b18](https://user-images.githubusercontent.com/6516307/41093281-339959d0-6a4b-11e8-83c5-b5d8afaca97d.jpg)

Indico offers us fixed limit of colors mostly light. If we change the color of the text inside it would make it more readable.

**Comment by mvassilev** [comment]
Fixed
