### ISSUE TITLE
Reload session=crash

### ISSUE THREAD

**Issue by Axel-Naumann** [vgvassilev/hepcon-config#28]
On Android, when reloading a session's view by pulling it down until the spinner shows: instead of reloading the app exits (crashes, presumably)

**Comment by vgvassilev** [comment]
Thanks for the report. That's fixed in the new release (happened a few hours ago). You should be able to update.

**Comment by Axel-Naumann** [comment]
Yup thanks! Now it's not crashing anymore but displays the spinner virtually eternally. But good enough for now, thanks!
